server:
  port: 8088

spring:
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  devtools:
    restart:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: root
    password: root
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
        format_sql: true
  jackson:
    serialization:
      fail-on-empty-beans: false
    default-property-inclusion: non_absent
  redis:
    host: localhost
    port: 6379
  data:
    redis:
      repositories:
        enabled: false

logging:
  level:
#    root: INFO
    com.webauthn.controller: DEBUG
    com.webauthn.service: DEBUG
    org.hibernate.type.descriptor:
            sql: trace